/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.java.testing.mockito;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.InMemoryExecutionContext;
import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.test.TypeValidation;

import static org.openrewrite.java.Assertions.java;

class PowerMockWhiteboxInvokeConstructorToJavaReflectionTest implements RewriteTest {
    @Override
    public void defaults(RecipeSpec spec) {
        spec
          .parser(JavaParser.fromJavaVersion()
            .logCompilationWarningsAndErrors(true)
            .classpathFromResources(new InMemoryExecutionContext(),
              "powermock-core-1",
              "powermock-reflect-1"
            ))
          .recipe(new PowerMockWhiteboxInvokeConstructorToJavaReflection());
    }

    @DocumentExample
    @Test
    void invokeConstructorNoArgs() {
        //language=java
        rewriteRun(
          // The user type used as a generic/result type is generated by the template and cannot be
          // attributed by the isolated template parser (a test-only artifact); the source is valid Java.
          spec -> spec.typeValidationOptions(TypeValidation.builder().identifiers(false).methodInvocations(false).build()),
          java(
            """
              class MyService {
                  private MyService() {
                  }
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void test() {
                      MyService s = Whitebox.invokeConstructor(MyService.class);
                  }
              }
              """,
            """
              import java.lang.reflect.Constructor;

              class MyServiceTest {
                  void test() throws Exception {
                      Constructor<MyService> myServiceConstructor = MyService.class.getDeclaredConstructor();
                      myServiceConstructor.setAccessible(true);
                      MyService s = myServiceConstructor.newInstance();
                  }
              }
              """
          )
        );
    }

    @Test
    void invokeConstructorWithResolvedParamTypes() {
        //language=java
        rewriteRun(
          spec -> spec.typeValidationOptions(TypeValidation.builder().identifiers(false).methodInvocations(false).build()),
          java(
            """
              class MyService {
                  private MyService(String name, int age) {
                  }
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void test() {
                      MyService s = Whitebox.invokeConstructor(MyService.class, "Alice", 42);
                  }
              }
              """,
            """
              import java.lang.reflect.Constructor;

              class MyServiceTest {
                  void test() throws Exception {
                      Constructor<MyService> myServiceConstructor = MyService.class.getDeclaredConstructor(String.class, int.class);
                      myServiceConstructor.setAccessible(true);
                      MyService s = myServiceConstructor.newInstance("Alice", 42);
                  }
              }
              """
          )
        );
    }

    @Test
    void invokeConstructorExplicitParamTypes() {
        //language=java
        rewriteRun(
          spec -> spec.typeValidationOptions(TypeValidation.builder().identifiers(false).methodInvocations(false).build()),
          java(
            """
              class MyService {
                  private MyService(String name, int age) {
                  }
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void test() {
                      MyService s = Whitebox.invokeConstructor(MyService.class, new Class[]{String.class, int.class}, new Object[]{"Alice", 42});
                  }
              }
              """,
            """
              import java.lang.reflect.Constructor;

              class MyServiceTest {
                  void test() throws Exception {
                      Constructor<MyService> myServiceConstructor = MyService.class.getDeclaredConstructor(String.class, int.class);
                      myServiceConstructor.setAccessible(true);
                      MyService s = myServiceConstructor.newInstance("Alice", 42);
                  }
              }
              """
          )
        );
    }

    @Test
    void invokeConstructorAsStatement() {
        //language=java
        rewriteRun(
          spec -> spec.typeValidationOptions(TypeValidation.builder().identifiers(false).methodInvocations(false).build()),
          java(
            """
              class MyService {
                  private MyService(String name) {
                  }
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void test() {
                      Whitebox.invokeConstructor(MyService.class, "Alice");
                  }
              }
              """,
            """
              import java.lang.reflect.Constructor;

              class MyServiceTest {
                  void test() throws Exception {
                      Constructor<MyService> myServiceConstructor = MyService.class.getDeclaredConstructor(String.class);
                      myServiceConstructor.setAccessible(true);
                      myServiceConstructor.newInstance("Alice");
                  }
              }
              """
          )
        );
    }

    @Test
    void invokeConstructorVarargsArrayNotMigrated() {
        //language=java
        rewriteRun(
          java(
            """
              class MyService {
                  private MyService(String a, String b) {
                  }
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void test() throws Exception {
                      MyService s = Whitebox.invokeConstructor(MyService.class, new Object[]{"a", "b"});
                  }
              }
              """
          )
        );
    }
}
