/*
 * Copyright 2026 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.java.testing.mockito;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.InMemoryExecutionContext;
import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.test.TypeValidation;

import static org.openrewrite.java.Assertions.java;

class PowerMockWhiteboxToJavaReflectionTest implements RewriteTest {
    @Override
    public void defaults(RecipeSpec spec) {
        spec
          .parser(JavaParser.fromJavaVersion()
            .logCompilationWarningsAndErrors(true)
            .classpathFromResources(new InMemoryExecutionContext(),
              "powermock-core-1",
              "powermock-reflect-1"
            ))
          .recipeFromResources("org.openrewrite.java.testing.mockito.PowerMockWhiteboxToJavaReflection");
    }

    @DocumentExample
    @Test
    void setInternalStateReplacedWithReflection() {
        //language=java
        rewriteRun(
          java(
            """
              class MyService {
                  private String name;
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void testSetField() {
                      MyService service = new MyService();
                      Whitebox.setInternalState(service, "name", "expectedValue");
                  }
              }
              """,
            """
              import java.lang.reflect.Field;

              class MyServiceTest {
                  void testSetField() throws Exception {
                      MyService service = new MyService();
                      Field nameField = service.getClass().getDeclaredField("name");
                      nameField.setAccessible(true);
                      nameField.set(service, "expectedValue");
                  }
              }
              """
          )
        );
    }

    @Test
    void mixedWhiteboxApisInSameMethod() {
        //language=java
        rewriteRun(
          // The user type used as a generic/result type is generated by the template and cannot be
          // attributed by the isolated template parser (a test-only artifact); the source is valid Java.
          spec -> spec.typeValidationOptions(TypeValidation.builder().identifiers(false).methodInvocations(false).build()),
          java(
            """
              class MyService {
                  private String name;
                  private String compute() { return name; }
              }
              """
          ),
          java(
            """
              import org.powermock.reflect.Whitebox;

              class MyServiceTest {
                  void test() {
                      MyService service = new MyService();
                      Whitebox.setInternalState(service, "name", "newValue");
                      String name = Whitebox.getInternalState(service, "name");
                      String result = Whitebox.invokeMethod(service, "compute");
                      MyService copy = Whitebox.invokeConstructor(MyService.class);
                  }
              }
              """,
            """
              import java.lang.reflect.Constructor;
              import java.lang.reflect.Field;
              import java.lang.reflect.Method;

              class MyServiceTest {
                  void test() throws Exception {
                      MyService service = new MyService();
                      Field nameField = service.getClass().getDeclaredField("name");
                      nameField.setAccessible(true);
                      nameField.set(service, "newValue");
                      Field nameField1 = service.getClass().getDeclaredField("name");
                      nameField1.setAccessible(true);
                      String name = (String) nameField1.get(service);
                      Method computeMethod = service.getClass().getDeclaredMethod("compute");
                      computeMethod.setAccessible(true);
                      String result = (String) computeMethod.invoke(service);
                      Constructor<MyService> myServiceConstructor = MyService.class.getDeclaredConstructor();
                      myServiceConstructor.setAccessible(true);
                      MyService copy = myServiceConstructor.newInstance();
                  }
              }
              """
          )
        );
    }

    @Test
    void noChangeWhenWhiteboxNotUsed() {
        //language=java
        rewriteRun(
          java(
            """
              class MyServiceTest {
                  void test() {
                  }
              }
              """
          )
        );
    }
}
